version: '3.7'

services:
  web:
    build: '.'
    depends_on:
    - db
    restart: always
    volumes:
    - type: bind
      source: ./src
      target: /var/www/html
    ports:
    - target: 80
      published: 8080
      protocol: tcp
      mode: host
    links:
    - "db:maindb"
  db:
    image: mysql:latest
    restart: always
    volumes:
    - type: bind
      source: ./database_data
      target: /var/lib/mysql
    - type: bind
      source: ./db_script
      target: /docker-entrypoint-initdb.d
    ports:
    - "3306:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=db_product